# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='expand',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='minscale',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='nocheck',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='pad',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='quiet',
        ),
    ]
