# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170718_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='parallel',
            field=models.IntegerField(default=0, help_text='number of parallel CPUs to use'),
        ),
    ]
