# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:00
from __future__ import unicode_literals

import api.extrafunc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parameters_parallel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='parallel',
        ),
        migrations.AddField(
            model_name='parameters',
            name='image',
            field=models.ImageField(help_text='the uploaded image need to be binarized', null=True, upload_to='', validators=[api.extrafunc.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='parameters',
            name='minscale',
            field=models.FloatField(default=1.0, help_text='minimum scale permitted'),
        ),
    ]
