# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:07
from __future__ import unicode_literals

import api.extrafunc
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='the uploaded image need to be binarized', null=True, upload_to='', validators=[api.extrafunc.validate_image_extension])),
                ('threshold', models.FloatField(default=0.5, help_text='threshold determines lightness')),
                ('zoom', models.FloatField(default=0.5, help_text='zoom for page background estimation')),
                ('escale', models.FloatField(default=1.0, help_text='scale for estimating a mask over the text region')),
                ('bignore', models.FloatField(default=0.1, help_text='ignore this much of the border for threshold estimation')),
                ('perc', models.FloatField(default=80.0, help_text='percentage for filters')),
                ('range', models.IntegerField(default=20, help_text='range for filters')),
                ('maxskew', models.FloatField(default=2.0, help_text='skew angle estimation parameters')),
                ('lo', models.FloatField(default=5.0, help_text='percentile for black estimation')),
                ('hi', models.FloatField(default=90.0, help_text='percentile for white estimation')),
                ('skewsteps', models.IntegerField(default=8, help_text='steps for skew angle estimation (per degree)')),
            ],
        ),
    ]
