# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170704_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='nocheck',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='parallel',
        ),
    ]
