# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:09
from __future__ import unicode_literals

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_parameters_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='image',
            field=models.ImageField(null=True, upload_to='', validators=[api.validators.validate_image_extension]),
        ),
    ]
