# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_parameters_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='parallel',
        ),
    ]
