# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 18:11
from __future__ import unicode_literals

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_parameters_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='image',
            field=models.ImageField(blank=True, help_text='the uploaded image need to be binarized', null=True, upload_to='', validators=[api.validators.validate_image_extension]),
        ),
    ]
