# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nolineest', models.BooleanField(default=True, help_text='target line height (do not overrides recognizer)')),
                ('height', models.IntegerField(default=-1, help_text='target line height (do not overrides recognizer)')),
                ('pad', models.IntegerField(default=16, help_text='extra blank padding to the left and right of text line')),
                ('nonormalize', models.BooleanField(default=True, help_text="don't normalize the textual output from the recognizer")),
                ('llocs', models.BooleanField(default=True, help_text='output LSTM locations for characters')),
                ('alocs', models.BooleanField(default=True, help_text='output aligned LSTM locations for characters')),
                ('probabilities', models.BooleanField(default=True, help_text='output probabilities for each letter')),
                ('estrate', models.BooleanField(default=True, help_text='estimate error rate only')),
                ('estconf', models.IntegerField(default=8, help_text='estimate confusion matrix')),
                ('compare', models.CharField(default='nospace', help_text='string comparison used for error rate estimate', max_length=50)),
                ('context', models.IntegerField(default=True, help_text='context for error reporting')),
                ('quiet', models.BooleanField(default=True, help_text='be less verbose, usally use with parallel together')),
                ('nocheck', models.BooleanField(default=True, help_text='disable error checking on inputs')),
                ('parallel', models.IntegerField(default=0, help_text='number of parallel processes to use')),
            ],
        ),
    ]
