# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='probabilities',
        ),
        migrations.AddField(
            model_name='parameters',
            name='prob',
            field=models.BooleanField(default=False, help_text='output probabilities for each letter'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='alocs',
            field=models.BooleanField(default=False, help_text='output aligned LSTM locations for characters'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='context',
            field=models.IntegerField(default=0, help_text='context for error reporting'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='estrate',
            field=models.BooleanField(default=False, help_text='estimate error rate only'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='height',
            field=models.IntegerField(default=-1, help_text='target line height (overrides recognizer)'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='llocs',
            field=models.BooleanField(default=False, help_text='output LSTM locations for characters'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='nolineest',
            field=models.BooleanField(default=False, help_text='target line height (overrides recognizer)'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='nonormalize',
            field=models.BooleanField(default=False, help_text="don't normalize the textual output from the recognizer"),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='quiet',
            field=models.BooleanField(default=False, help_text='be less verbose, usally use with parallel together'),
        ),
    ]
