# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170705_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='prob',
            new_name='probabilities',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='alocs',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='compare',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='context',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='estconf',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='estrate',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='nocheck',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='nolineest',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='quiet',
        ),
    ]
