# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parameters_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='model',
        ),
    ]
