# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170723_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='model',
            field=models.FileField(default='/static//models/en-default.pyrnn.gz', help_text='line recognition model', upload_to='model'),
        ),
    ]
