# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_parameters_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='image',
        ),
    ]
